# Generated by Django 6.1.1 on 2026-09-29 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_phone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='HeadPharmacist',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('head_pharmacist_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('head_pharmacist_phone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'head_pharmacist',
            },
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('pharmacist_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('pharmacist_phone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pharmacist',
            },
        ),
    ]
