"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

# added - 09292026
import mimetypes
from pathlib import Path
 
from decouple import config as env
 
# Windows fix: some installed software rewrites the registry so ".css" is served as
# "text/plain". Chrome then refuses to apply the stylesheet (page looks unstyled).
# Forcing the correct types makes CSS/JS load on every machine.
mimetypes.add_type("text/css", ".css", True)
mimetypes.add_type("text/javascript", ".js", True)
 
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
 
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=by9v83t$t0g8*6e&v+83w$&g3smt)v!yb)i#wch$vz_o-!1%%'
 
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
 
ALLOWED_HOSTS = []
 
 
# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "apps.login",
    "apps.register",
    "apps.landing",
    "apps.home",
    "apps.profiles",
    "apps.user_settings",
]
 
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
 
ROOT_URLCONF = 'config.urls'
 
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
 
WSGI_APPLICATION = 'config.wsgi.application'
 
 
# Database (credentials come from the .env file)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
    }
}
 
 
# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]
 
 
# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True
 
 
# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
 
 
# Email
MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
 
LOGIN_URL = 'login:login'
LOGIN_REDIRECT_URL = 'home:home'
LOGOUT_REDIRECT_URL = 'login:login'
 
# Custom user model (ERD "User" table) - must be set BEFORE the first migrate
AUTH_USER_MODEL = "register.User"
 
# edited - 09292026
# from pathlib import Path
 
# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
 
 
# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/
 
# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-=by9v83t$t0g8*6e&v+83w$&g3smt)v!yb)i#wch$vz_o-!1%%'
 
# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
 
# ALLOWED_HOSTS = []
 
 
# # Application definition
 
# # INSTALLED_APPS = [
# #     'django.contrib.admin',
# #     'django.contrib.auth',
# #     'django.contrib.contenttypes',
# #     'django.contrib.sessions',
# #     'django.contrib.messages',
# #     'django.contrib.staticfiles',
# #     "accounts", # added
# #     "dashboard", # added
# # ]
 
# # edited
# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     "apps.login",
#     "apps.register",
#     "apps.landing",
#     "apps.home",
#     "apps.profiles",
#     "apps.user_settings",
# ]
 
# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]
 
# ROOT_URLCONF = 'config.urls'
 
# TEMPLATES = [
#     {
#         # 'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         # 'DIRS': [],
#         # 'APP_DIRS': True,
#         "BACKEND": "django.template.backends.django.DjangoTemplates",
#         "DIRS": [BASE_DIR / "templates"],
#         "APP_DIRS": True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]
 
# WSGI_APPLICATION = 'config.wsgi.application'
 
 
# # Database
# # https://docs.djangoproject.com/en/6.1/ref/settings/#databases
 
# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.sqlite3',
# #         'NAME': BASE_DIR / 'db.sqlite3',
# #     }
# # }
 
# from decouple import config as env
 
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": env("DB_NAME"),
#         "USER": env("DB_USER"),
#         "PASSWORD": env("DB_PASSWORD"),
#         "HOST": env("DB_HOST"),
#         "PORT": env("DB_PORT"),
#     }
# }
 
 
# # Password validation
# # https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators
 
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]
 
 
# # Internationalization
# # https://docs.djangoproject.com/en/6.1/topics/i18n/
 
# LANGUAGE_CODE = 'en-us'
 
# TIME_ZONE = 'UTC'
 
# USE_I18N = True
 
# USE_TZ = True
 
 
# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/6.1/howto/static-files/
 
# # STATIC_URL = 'static/'
 
# # added
# # STATIC_URL = "static/"
# # STATICFILES_DIRS = [BASE_DIR / "static"]
 
# # # edited
# # # Static files (CSS, JavaScript, Images)
# # STATIC_URL = '/static/'
# # # Tell Django where to find static files during development
# # STATICFILES_DIRS = [
# #     BASE_DIR / 'static',
# # ]
# # # If you run collectstatic in production:
# # STATIC_ROOT = BASE_DIR / 'staticfiles'
 
# # edited pt 2
# STATIC_URL = 'static/'
# STATICFILES_DIRS = [
#     BASE_DIR / 'static',
# ]
# STATIC_ROOT = BASE_DIR / 'staticfiles'
 
 
# # Email
# # https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
 
# MAILERS = {
#     'default': {
#         'BACKEND': 'django.core.mail.backends.console.EmailBackend',
#     },
# }
 
# # added
# # LOGIN_REDIRECT_URL = "home"
# # LOGIN_URL = "login"
# # LOGOUT_REDIRECT_URL = "login"
 
# # edited
# # LOGIN_URL = 'login'
# # LOGIN_REDIRECT_URL = '/home/'  # Matches your dashboard URL path
# # LOGOUT_REDIRECT_URL = 'login'
 
# # edited pt 2
# LOGIN_URL = 'login:login'
# LOGIN_REDIRECT_URL = 'home:home'
# LOGOUT_REDIRECT_URL = 'login:login'
 
# # added - 09292026
# # Custom user model (ERD "User" table) - must be set BEFORE the first migrate
# AUTH_USER_MODEL = "register.User"